CREATE TABLE users (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 display_name VARCHAR(60) NOT NULL, created_at DATETIME(6) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE characters (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE,
 total_xp BIGINT NOT NULL DEFAULT 0 CHECK(total_xp BETWEEN 0 AND 1000000000),
 gold BIGINT NOT NULL DEFAULT 0 CHECK(gold BETWEEN 0 AND 1000000000),
 streak INT NOT NULL DEFAULT 0 CHECK(streak>=0), best_streak INT NOT NULL DEFAULT 0 CHECK(best_streak>=0),
 last_activity_date DATE, last_activity_at DATETIME(6), day_window_end DATETIME(6),
 timezone VARCHAR(80) NOT NULL, pending_timezone VARCHAR(80), avatar VARCHAR(20) NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE character_attributes (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL,
 type VARCHAR(20) NOT NULL, xp BIGINT NOT NULL DEFAULT 0 CHECK(xp BETWEEN 0 AND 1000000000),
 UNIQUE(character_id,type), FOREIGN KEY(character_id) REFERENCES characters(id)
) ENGINE=InnoDB;
CREATE TABLE tasks (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL,
 title VARCHAR(120) NOT NULL, description VARCHAR(1000),
 category VARCHAR(20) NOT NULL, difficulty VARCHAR(10) NOT NULL, due_date DATE,
 completed BIT NOT NULL DEFAULT 0, archived BIT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, completed_at DATETIME(6),
 FOREIGN KEY(user_id) REFERENCES users(id), INDEX tasks_owner(user_id,archived,completed,id)
) ENGINE=InnoDB;
CREATE TABLE task_completions (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, task_id BIGINT NOT NULL UNIQUE, user_id BIGINT NOT NULL,
 title VARCHAR(120) NOT NULL, category VARCHAR(20) NOT NULL,
 xp INT NOT NULL CHECK(xp>0), gold INT NOT NULL CHECK(gold>0),
 completed_at DATETIME(6) NOT NULL, local_date DATE NOT NULL, timezone VARCHAR(80) NOT NULL,
 FOREIGN KEY(task_id) REFERENCES tasks(id), FOREIGN KEY(user_id) REFERENCES users(id),
 INDEX completions_owner(user_id,id)
) ENGINE=InnoDB;
CREATE TABLE activity_days (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL,
 local_date DATE NOT NULL, timezone VARCHAR(80) NOT NULL,
 window_start DATETIME(6) NOT NULL, window_end DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL,
 UNIQUE(character_id,window_start), FOREIGN KEY(character_id) REFERENCES characters(id)
) ENGINE=InnoDB;
CREATE TABLE shop_items (
 id BIGINT NOT NULL PRIMARY KEY, name VARCHAR(60) NOT NULL, slot VARCHAR(10) NOT NULL,
 appearance VARCHAR(30) NOT NULL, description VARCHAR(200) NOT NULL, price INT NOT NULL CHECK(price>0)
) ENGINE=InnoDB;
CREATE TABLE inventory (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, character_id BIGINT NOT NULL, item_id BIGINT NOT NULL,
 equipped BIT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL,
 UNIQUE(character_id,item_id), FOREIGN KEY(character_id) REFERENCES characters(id), FOREIGN KEY(item_id) REFERENCES shop_items(id)
) ENGINE=InnoDB;
CREATE TABLE economy_ledger (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, kind VARCHAR(20) NOT NULL,
 description VARCHAR(160) NOT NULL, xp BIGINT NOT NULL, gold BIGINT NOT NULL,
 task_id BIGINT, item_id BIGINT, created_at DATETIME(6) NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(task_id) REFERENCES tasks(id), FOREIGN KEY(item_id) REFERENCES shop_items(id),
 INDEX ledger_owner(user_id,id)
) ENGINE=InnoDB;
CREATE TABLE SPRING_SESSION (
 PRIMARY_ID CHAR(36) NOT NULL, SESSION_ID CHAR(36) NOT NULL,
 CREATION_TIME BIGINT NOT NULL, LAST_ACCESS_TIME BIGINT NOT NULL, MAX_INACTIVE_INTERVAL INT NOT NULL,
 EXPIRY_TIME BIGINT NOT NULL, PRINCIPAL_NAME VARCHAR(100),
 CONSTRAINT SPRING_SESSION_PK PRIMARY KEY(PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION(SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION(EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION(PRINCIPAL_NAME);
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
 SESSION_PRIMARY_ID CHAR(36) NOT NULL, ATTRIBUTE_NAME VARCHAR(200) NOT NULL, ATTRIBUTE_BYTES BLOB NOT NULL,
 CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY(SESSION_PRIMARY_ID,ATTRIBUTE_NAME),
 CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY(SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
