import { Component, useEffect, useRef, useState } from 'react'
import type { ReactNode, FormEvent } from 'react'
import { NavLink, Navigate, Route, Routes, useLocation, Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, ArrowUpRight, Backpack, BookOpen, Check, ChevronLeft, ChevronRight, Circle, Coins, Compass, Flame, Gem, LayoutDashboard, LogOut, Menu, Plus, Shield, Sparkles, Store, Swords, Target, Trash2, UserRound, X, Pencil, Code2, Dumbbell, Brain, MessageCircle, Leaf, Trophy, Medal, Clock3 } from 'lucide-react'
import { api, ApiError, categories, label } from './api'
import type { Activity, Hero, Item, Leaderboard, LeaderboardEntry, Page, Quest, User } from './api'
import { Badge, Character } from './Character'

const categoryIcons: Record<string,typeof Code2> = { CODING:Code2, STUDY:BookOpen, EXERCISE:Dumbbell, READING:BookOpen, MEDITATION:Leaf, COMMUNICATION:MessageCircle }
const attributeIcons: Record<string,typeof Brain> = { INTELLECT:Brain, STRENGTH:Dumbbell, WISDOM:BookOpen, FOCUS:Target, CHARISMA:MessageCircle }
const nav = [['/','Overview',LayoutDashboard],['/quests','Quest journal',Compass],['/leaderboard','Leaderboard',Trophy],['/shop','The marketplace',Store],['/inventory','Inventory',Backpack],['/profile','Character & activity',UserRound]] as const
type Notice = { title:string; detail?:string }
export default function App() {
  const me = useQuery({queryKey:['me'],queryFn:()=>api<User>('/auth/me')})
  const location=useLocation()
  useEffect(()=>{
    let meta=document.querySelector<HTMLMetaElement>('meta[name="robots"]')
    if(!meta){meta=document.createElement('meta');meta.name='robots';document.head.appendChild(meta)}
    meta.content=me.data?'noindex,nofollow':'index,follow'
    document.title=(nav.find(n=>n[0]===location.pathname)?.[1] || 'Welcome')+' — LevelForge'
  },[me.data,location.pathname])
  if(me.isPending)return <div className="boot"><Brand/><Loading/></div>
  if(me.error && !(me.error instanceof ApiError && me.error.status===401)) return <div className="boot"><Brand/><ErrorPanel error={me.error} retry={()=>me.refetch()}/></div>
  return <Boundary key={me.data?.id || 'guest'}>{me.data?<Game user={me.data}/>:<Public/>}</Boundary>
}
function Brand(){return <Link className="brand" to="/"><span className="brand-mark"><Swords size={23}/></span><span>Level<span className="gold-text">Forge</span><small>MAKE EVERY DAY AN ADVENTURE</small></span></Link>}
function Loading(){return <div className="loading" aria-label="Loading" role="status"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div>}
function ErrorPanel({error,retry}:{error:Error;retry:()=>void}){return <div className="error-box" role="alert"><p>{error.message}</p><button className="button subtle" onClick={retry}>Try again</button></div>}
class Boundary extends Component<{children:ReactNode},{failed:boolean}> {
  state={failed:false}
  static getDerivedStateFromError(){return {failed:true}}
  render(){return this.state.failed?<div className="boot"><h1>The page hit a snag.</h1><p>Your saved progress is safe on the server.</p><button className="button" onClick={()=>window.location.reload()}>Reload LevelForge</button></div>:this.props.children}
}
function Public(){
  const [signup,setSignup]=useState(false)
  const query=useQueryClient()
  const auth=useMutation({mutationFn:(body:unknown)=>api<User>('/auth/'+(signup?'signup':'login'),'POST',body),onSuccess:(user)=>{query.setQueryData(['me'],user);void query.invalidateQueries({queryKey:['character']})}})
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));auth.mutate({...data,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})}
  return <div className="public"><header><Brand/><span className="tiny-label">A LITTLE ADVENTURE. REAL PROGRESS.</span></header><main className="public-grid">
    <section className="public-story"><span className="eyebrow"><span className="dot"/> YOUR LIFE. YOUR NEXT CHAPTER.</span><h1>Great adventures<br/>begin with <em>small<br/>steps.</em></h1><p>Turn the things you want to do into quests worth completing. Build your character as you build a better everyday.</p><div className="public-loop"><span><Compass/>Set a quest</span><ArrowRight/><span><Sparkles/>Earn your XP</span><ArrowRight/><span><Trophy/>Climb together</span></div><div className="story-art"><Character/><div><span className="eyebrow">MEET YOUR FUTURE SELF</span><h3>A work in progress.<br/>An adventurer at heart.</h3><p>Share the journey with fellow adventurers.<br/>Every honest step moves you forward.</p></div></div></section>
    <section className="auth-card"><span className="small-emblem"><Swords/></span><span className="eyebrow">YOUR ADVENTURE AWAITS</span><h2>{signup?'Start your story.':'Welcome back, adventurer.'}</h2><p>{signup?'A fresh character. A world of possibility.':'Your next chapter is right where you left it.'}</p><div className="auth-tabs"><button className={!signup?'active':''} onClick={()=>{setSignup(false);auth.reset()}}>Sign in</button><button className={signup?'active':''} onClick={()=>{setSignup(true);auth.reset()}}>Create account</button></div>
    <form onSubmit={submit}>{signup&&<label>Adventurer name<input name="displayName" autoComplete="nickname" required maxLength={60} placeholder="What should we call you?"/></label>}<label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><label>Password<input name="password" type="password" autoComplete={signup?'new-password':'current-password'} required minLength={signup?10:1} maxLength={72} placeholder={signup?'At least 10 characters':'Your password'}/></label>{signup&&<small>Your timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Change it in your profile.</small>}{auth.error&&<p className="form-error" role="alert">{auth.error.message}</p>}<button className="button full" disabled={auth.isPending}>{auth.isPending?'Opening your journal…':signup?'Begin my adventure':'Return to my adventure'}<ArrowRight size={18}/></button></form><p className="auth-note"><Shield size={15}/> Progress saved securely. Always yours.</p></section>
  </main><footer>LEVELFORGE <span>Real-life effort. A little everyday magic.</span><small>Completion is self-reported. Every honest step counts.</small></footer></div>
}
function Game({user}:{user:User}){
  const client=useQueryClient()
  const hero=useQuery({queryKey:['character'],queryFn:()=>api<Hero>('/character'),refetchInterval:30000})
  const [menu,setMenu]=useState(false),[notice,setNotice]=useState<Notice|null>(null),[editor,setEditor]=useState<Quest|'new'|null>(null)
  const location=useLocation()
  useEffect(()=>setMenu(false),[location.pathname])
  useEffect(()=>{
    if(!menu)return
    document.getElementById('close-navigation')?.focus()
    const keys=(event:KeyboardEvent)=>{
      if(event.key==='Escape'){setMenu(false);return}
      if(event.key!=='Tab')return
      const elements=Array.from(document.querySelectorAll<HTMLElement>('.sidebar a, .sidebar button:not(:disabled)'))
      const first=elements[0],last=elements[elements.length-1]
      if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}
      if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}
    }
    document.addEventListener('keydown',keys)
    return()=>{document.removeEventListener('keydown',keys);document.getElementById('open-navigation')?.focus()}
  },[menu])
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(null),4500);return()=>clearTimeout(t)},[notice])
  useEffect(()=>{if(hero.error instanceof ApiError&&hero.error.status===401)void client.invalidateQueries({queryKey:['me']})},[hero.error,client])
  const refresh=()=>{void client.invalidateQueries()}
  const logout=useMutation({mutationFn:()=>api('/auth/logout','POST'),onSuccess:()=>{client.clear();window.location.assign('/')},onError:e=>setNotice({title:e.message})})
  const theme=hero.data?.cosmetics.find(i=>i.slot==='THEME')?.appearance || 'default'
  const heading=nav.find(n=>n[0]===location.pathname)?.[1] || 'Overview'
  return <div className={'app theme-'+theme}>
    <aside className={'sidebar '+(menu?'open':'')}><Brand/><button className="icon-button close-menu" id="close-navigation" aria-label="Close navigation" onClick={()=>setMenu(false)}><X/></button><div className="nav-caption">YOUR ADVENTURE</div><nav aria-label="Main navigation">{nav.map(([path,name,Icon])=><NavLink key={path} to={path} end><Icon size={19}/>{name}{path==='/'&&<span className="nav-diamond"/>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="quote"><Sparkles size={18}/><p>“A little progress each day<br/>adds up to a great adventure.”</p><span>KEEP SHOWING UP.</span></div><div className="sidebar-user"><Character small avatar={hero.data?.avatar}/><div><strong>{user.displayName}</strong><small>Level {hero.data?.progress.level || 1} adventurer</small></div><button className="icon-button" aria-label="Sign out" disabled={logout.isPending} onClick={()=>logout.mutate()}><LogOut size={17}/></button></div></div></aside>
    {menu&&<button className="menu-backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}
    <div className="workspace" inert={menu}><header className="topbar"><div><button className="icon-button mobile-menu" id="open-navigation" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu/></button><span className="breadcrumb">Your adventure <ChevronRight size={13}/> <strong>{heading}</strong></span></div><div className="top-stats"><span><Flame size={16}/>{hero.data?.streak || 0}<small> day streak</small></span><span className="gold-text"><Coins size={17}/>{hero.data?.gold ?? '—'}<small> Gold</small></span></div></header>
    <main className="content">{hero.isPending?<Loading/>:hero.error?<ErrorPanel error={hero.error} retry={()=>hero.refetch()}/>:hero.data&&<Routes>
      <Route path="/" element={<Dashboard hero={hero.data} onNew={()=>setEditor('new')} edit={setEditor} notify={setNotice} refresh={refresh}/>}/>
      <Route path="/quests" element={<QuestJournal onNew={()=>setEditor('new')} edit={setEditor} notify={setNotice} refresh={refresh}/>}/>
      <Route path="/leaderboard" element={<LeaderboardPage/>}/>
      <Route path="/shop" element={<Shop hero={hero.data} inventoryOnly={false} notify={setNotice} refresh={refresh}/>}/>
      <Route path="/inventory" element={<Shop hero={hero.data} inventoryOnly notify={setNotice} refresh={refresh}/>}/>
      <Route path="/profile" element={<Profile hero={hero.data} user={user} notify={setNotice} refresh={refresh} logout={()=>logout.mutate()}/>}/>
      <Route path="*" element={<Navigate to="/" replace/>}/>
    </Routes>}<footer className="app-footer"><span><Swords size={13}/> Built one quest at a time.</span><span>YOUR PROGRESS, YOUR PACE.</span></footer></main></div>
    {editor&&<QuestEditor quest={editor==='new'?undefined:editor} close={()=>setEditor(null)} saved={()=>{setEditor(null);refresh();setNotice({title:editor==='new'?'A new quest awaits.':'Quest updated.'})}}/>}
    <AnimatePresence>{notice&&<motion.div className="toast" role="status" aria-live="polite" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}}><span className="toast-icon"><Sparkles/></span><div><strong>{notice.title}</strong>{notice.detail&&<p>{notice.detail}</p>}</div><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice(null)}><X size={17}/></button></motion.div>}</AnimatePresence>
  </div>
}
type QuestActions={edit:(q:Quest)=>void;notify:(n:Notice)=>void;refresh:()=>void}
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function NewButton({onClick}:{onClick:()=>void}){return <button className="button" onClick={onClick}><Plus size={18}/> New quest</button>}
function Dashboard({hero,onNew,...actions}:{hero:Hero;onNew:()=>void}&QuestActions){
  const quests=useQuery({queryKey:['quests','dashboard'],queryFn:()=>api<Page<Quest>>('/tasks?status=pending&sort=due&size=5')})
  const activity=useQuery({queryKey:['activity','recent'],queryFn:()=>api<Page<Activity>>('/activity?size=4')})
  const badge=hero.cosmetics.find(i=>i.slot==='BADGE')
  return <><PageHeading eyebrow="A NEW DAY. A NEW POSSIBILITY." title={'Good to see you, '+hero.displayName+'.'} description="Every small step is part of a bigger story. What will yours be today?" action={<NewButton onClick={onNew}/>}/>
  <div className="dashboard-grid"><section className="hero-card panel"><div className="hero-portrait"><Character avatar={hero.avatar} cosmetics={hero.cosmetics}/><span className="portrait-label"><span className="dot"/> THE ADVENTURER</span></div><div className="hero-detail"><span className="eyebrow">YOUR CHARACTER</span><h2>{hero.displayName} {badge&&<Badge appearance={badge.appearance}/>}</h2><p className="hero-class">{label(hero.avatar)} · {hero.progress.level<3?'The journey begins':'Finding your stride'}</p><div className="level-line"><span className="level-shield">{hero.progress.level}</span><div><strong>Level {hero.progress.level}</strong><small>{hero.progress.required-hero.progress.current} XP to your next chapter</small></div><Sparkles size={21} className="gold-text"/></div><div className="xp-label"><span>LEVEL PROGRESS</span><strong>{hero.progress.current} <span>/ {hero.progress.required} XP</span></strong></div><div className="progress-track"><motion.div initial={false} animate={{width:(hero.progress.current/hero.progress.required*100)+'%'}} transition={{duration:.5}}/></div><div className="hero-metrics"><div><Coins className="gold-text"/><span><strong>{hero.gold}<small> Gold</small></strong><small>A little effort, well earned</small></span></div><div><Gem className="teal-text"/><span><strong>{hero.progress.total}<small> XP</small></strong><small>Lifetime experience</small></span></div></div></div></section>
  <section className="streak-card panel"><div className="section-kicker"><span>KEEP THE FIRE GOING</span><Flame size={17}/></div><div className="streak-number">{hero.streak}<span>day streak</span></div><p>{hero.streak?'One quest today keeps your momentum alive.':'Your first completed quest lights the spark.'}</p><div className="streak-message"><Flame size={16}/><strong>Personal best</strong><span>{hero.bestStreak} days</span></div><div className="streak-foot"><span className="dot"/>{hero.streak?'Progress is a practice. Keep going.':'A fresh start is a powerful thing.'}</div></section>
  <section className="quest-panel panel"><div className="section-heading"><div><h2>Your next quests <span className="count">{quests.data?.totalElements || 0}</span></h2><p>A little focus. A meaningful step forward.</p></div><Link className="text-link" to="/quests">View journal <ArrowUpRight size={15}/></Link></div>{quests.isPending?<Loading/>:quests.error?<ErrorPanel error={quests.error} retry={()=>quests.refetch()}/>:quests.data?.content.length?quests.data.content.map(q=><QuestRow key={q.id} quest={q} {...actions}/>):<Empty icon={Compass} title="Your next chapter starts with a quest." text="Read a chapter, move your body, or learn something new." action={<button className="button subtle" onClick={onNew}><Plus size={16}/> Create a quest</button>}/>}<button className="add-row" onClick={onNew}><Plus size={16}/> Make room for another small win</button></section>
  <section className="attributes panel"><div className="section-heading"><div><h2>Your attributes</h2><p>Grow in more ways than one.</p></div><Shield size={20} className="muted"/></div>{hero.attributes.map(a=>{const Icon=attributeIcons[a.type]||Brain;return <div className="attribute" key={a.type}><span className={'attribute-icon '+a.type.toLowerCase()}><Icon size={18}/></span><div><div><strong>{label(a.type)}</strong><span>Lv. {a.progress.level}</span></div><div className="attribute-track"><span style={{width:a.progress.current/a.progress.required*100+'%'}}/></div><small>{a.progress.current} / {a.progress.required} XP</small></div></div>})}<p className="attribute-tip"><Sparkles size={14}/> Different quests. A more balanced you.</p></section>
  <section className="recent panel"><div className="section-heading"><div><h2>Along the way</h2><p>The small wins that tell your story.</p></div><Link className="text-link" to="/profile">All activity <ArrowUpRight size={15}/></Link></div>{activity.isPending?<Loading/>:activity.error?<ErrorPanel error={activity.error} retry={()=>activity.refetch()}/>:<ActivityList items={activity.data?.content || []}/>}</section></div></>
}
function Empty({icon:Icon,title,text,action}:{icon:typeof Compass;title:string;text:string;action?:ReactNode}){return <div className="empty"><span><Icon size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>}
function QuestRow({quest:q,edit,notify,refresh}:QuestActions&{quest:Quest}){
  const [confirm,setConfirm]=useState(false),[details,setDetails]=useState(false)
  const mutation=useMutation({mutationFn:(kind:string)=>api<{applied:boolean;xp:number;gold:number;levelUp:boolean}>('/tasks/'+q.id+(kind==='complete'?'/complete':''),kind==='complete'?'POST':'DELETE'),onSuccess:(result,kind)=>{refresh();setConfirm(false);notify({title:kind==='complete'?(result.applied?(result.levelUp?'Level up! A new chapter begins.':'Quest complete. Well earned.'):'This quest is already complete.'):'Quest archived.',detail:result?.applied?'+'+result.xp+' XP · +'+result.gold+' Gold':undefined})},onError:e=>notify({title:e.message})})
  const Icon=categoryIcons[q.category]||Compass
  return <><div className={'quest-row '+(q.completed?'completed':'')}><button className="complete-button" disabled={q.completed||q.archived||mutation.isPending} aria-label={'Complete '+q.title} onClick={()=>mutation.mutate('complete')}>{q.completed?<Check size={18}/>:mutation.isPending?<span className="spinner"/>:<Circle size={20}/>}</button><span className={'quest-icon '+q.category.toLowerCase()}><Icon size={19}/></span><button className="quest-info" onClick={()=>setDetails(true)}><strong>{q.title}</strong><span>{label(q.category)}<i/> {label(q.difficulty)} {q.dueDate&&<><i/>Due {q.dueDate}</>}{q.completed&&<><i/>Completed</>}{q.archived&&<><i/>Archived</>}</span></button><div className="quest-reward"><strong>+{q.rewardXp} <small>XP</small></strong><span><Coins size={12}/>{q.rewardGold}</span></div><div className="row-tools">{!q.completed&&!q.archived&&<button className="icon-button" aria-label={'Edit '+q.title} onClick={()=>edit(q)}><Pencil size={15}/></button>}{!q.archived&&<button className="icon-button" aria-label={'Archive '+q.title} onClick={()=>setConfirm(true)}><Trash2 size={15}/></button>}</div></div>
  {confirm&&<Dialog title="Archive this quest?" close={()=>setConfirm(false)}><p>“{q.title}” will move to your archive. Completed rewards and history are preserved.</p><div className="dialog-actions"><button className="button subtle" onClick={()=>setConfirm(false)}>Keep quest</button><button className="button danger" disabled={mutation.isPending} onClick={()=>mutation.mutate('archive')}>{mutation.isPending?'Archiving…':'Archive quest'}</button></div></Dialog>}
  {details&&<Dialog title={q.title} close={()=>setDetails(false)}><div className="detail-tags"><span>{label(q.category)}</span><span>{label(q.difficulty)}</span><span>{q.archived?'Archived':q.completed?'Completed':'Pending'}</span></div><p className="quest-description">{q.description||'No description added. A clear intention is a good place to start.'}</p><p className="gold-text">{q.rewardXp} XP · {q.rewardGold} Gold</p><p>Created {new Date(q.createdAt).toLocaleString()}</p>{q.dueDate&&<p>Due {q.dueDate}</p>}{q.completedAt&&<p>Completed {new Date(q.completedAt).toLocaleString()}</p>}{!q.completed&&!q.archived&&<button className="button" onClick={()=>{setDetails(false);edit(q)}}>Edit quest</button>}</Dialog>}</>
}
function QuestJournal({onNew,...actions}:{onNew:()=>void}&QuestActions){
  const [status,setStatus]=useState('pending'),[category,setCategory]=useState(''),[sort,setSort]=useState('newest'),[page,setPage]=useState(0)
  const quests=useQuery({queryKey:['quests',status,category,sort,page],queryFn:()=>api<Page<Quest>>('/tasks?'+new URLSearchParams({status,sort,page:String(page),...(category?{category}:{})}))})
  return <><PageHeading eyebrow="ONE INTENTION AT A TIME" title="Your quest journal" description="Give your goals a place to begin. Turn intention into experience." action={<NewButton onClick={onNew}/>}/><section className="panel journal"><div className="filters"><div className="tabs" aria-label="Quest status">{['pending','completed','archived'].map(s=><button key={s} aria-pressed={status===s} className={status===s?'active':''} onClick={()=>{setStatus(s);setPage(0)}}>{label(s)}</button>)}</div><div className="filter-selects"><label className="sr-only" htmlFor="category-filter">Category</label><select id="category-filter" value={category} onChange={e=>{setCategory(e.target.value);setPage(0)}}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><label className="sr-only" htmlFor="sort-filter">Sort quests</label><select id="sort-filter" value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="newest">Newest first</option><option value="due">Due date</option></select></div></div>{quests.isPending?<Loading/>:quests.error?<ErrorPanel error={quests.error} retry={()=>quests.refetch()}/>:quests.data?.content.length?<>{quests.data.content.map(q=><QuestRow key={q.id} quest={q} {...actions}/>)}<Pagination page={page} pages={quests.data.totalPages} setPage={setPage}/></>:<Empty icon={Compass} title={'No '+status+' quests here yet.'} text={status==='pending'?'Choose one thing you want to make progress on.':'Your journey will fill these pages in time.'} action={status==='pending'?<NewButton onClick={onNew}/>:undefined}/>}</section></>
}
function LeaderboardPage(){
  const [page,setPage]=useState(0),[tick,setTick]=useState(Date.now())
  const board=useQuery({queryKey:['leaderboard',page],queryFn:()=>api<Leaderboard>('/leaderboard?page='+page+'&size=25'),refetchInterval:15000})
  useEffect(()=>{const id=setInterval(()=>setTick(Date.now()),1000);return()=>clearInterval(id)},[])
  const remaining=board.data?Math.max(0,Math.floor((new Date(board.data.weekEnd).getTime()-tick)/1000)):0
  const time=Math.floor(remaining/86400)+'d '+String(Math.floor(remaining%86400/3600)).padStart(2,'0')+'h '+String(Math.floor(remaining%3600/60)).padStart(2,'0')+'m'
  const top=board.data?.rankings.page===0?board.data.rankings.content.slice(0,3):[]
  return <><PageHeading eyebrow="SEVEN DAYS. ONE SHARED ADVENTURE." title="Weekly leaderboard" description="Complete quests, earn weekly XP, and climb alongside every LevelForge adventurer." action={<div className="season-clock"><Clock3 size={19}/><div><small>WEEK RESETS IN</small><strong>{time}</strong></div></div>}/>
    {board.isPending?<Loading/>:board.error?<ErrorPanel error={board.error} retry={()=>board.refetch()}/>:board.data&&<>
      <section className="reward-strip panel"><div><Trophy/><span><strong>Top 10 earn a weekly XP bonus</strong><small>Complete at least one quest to qualify. Ties favor the earlier account.</small></span></div><div className="reward-chips"><span>#1 <b>+1000</b></span><span>#2 <b>+500</b></span><span>#3 <b>+200</b></span><span>#4–10 <b>+100</b></span></div></section>
      {top.length>0&&<section className="podium" aria-label="Top three adventurers">{[top[1],top[0],top[2]].filter(Boolean).map(entry=><LeaderboardCard key={entry.userId} entry={entry}/>)}</section>}
      <section className="panel ranking-panel"><div className="section-heading"><div><h2>All adventurers <span className="count">{board.data.rankings.totalElements}</span></h2><p>Ranks update automatically as quests are completed.</p></div><div className="your-rank"><small>YOUR RANK</small><strong>#{board.data.currentUser.rank}</strong><span>{board.data.currentUser.weeklyXp} XP</span></div></div>
        <div className="rank-list">{board.data.rankings.content.map(entry=><div className={'rank-row '+(entry.currentUser?'is-you':'')+(entry.rank<=10?' top-ten':'')} key={entry.userId}><span className="rank-number">{entry.rank<=3?<Medal size={20}/>:null}#{entry.rank}</span><Character avatar={entry.avatar} small/><div className="rank-person"><strong>{entry.displayName}{entry.currentUser&&<em>YOU</em>}</strong><small>Level {entry.progress.level} · {entry.progress.total} lifetime XP</small></div><div className="weekly-score"><strong>{entry.weeklyXp}</strong><small>WEEKLY XP</small></div><span className={'bonus '+(entry.projectedRewardXp?'active':'')}>{entry.projectedRewardXp?'+'+entry.projectedRewardXp+' bonus':'—'}</span></div>)}</div>
        <Pagination page={board.data.rankings.page} pages={board.data.rankings.totalPages} setPage={setPage}/>
      </section>
    </>}
  </>
}
function LeaderboardCard({entry}:{entry:LeaderboardEntry}){return <article className={'podium-card panel place-'+entry.rank+(entry.currentUser?' is-you':'')}><span className="podium-rank"><Trophy size={18}/> #{entry.rank}</span><Character avatar={entry.avatar}/><h2>{entry.displayName}</h2><p>Level {entry.progress.level}</p><strong>{entry.weeklyXp} XP</strong><small>Projected reward +{entry.projectedRewardXp} XP</small></article>}
function Dialog({title,close,children}:{title:string;close:()=>void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{const el=ref.current;const before=document.activeElement as HTMLElement;el?.showModal();return()=>{el?.close();before?.focus()}},[])
  return <dialog ref={ref} className="dialog" onCancel={e=>{e.preventDefault();close()}} aria-labelledby="dialog-title" onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="dialog-inner"><div className="dialog-heading"><h2 id="dialog-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={close}><X/></button></div>{children}</div></dialog>
}
function QuestEditor({quest,close,saved}:{quest?:Quest;close:()=>void;saved:()=>void}){
  const [difficulty,setDifficulty]=useState(quest?.difficulty||'MEDIUM')
  const mutation=useMutation({mutationFn:(body:unknown)=>api('/tasks'+(quest?'/'+quest.id:''),quest?'PATCH':'POST',body),onSuccess:saved})
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));mutation.mutate({...data,title:String(data.title).trim(),dueDate:data.dueDate||null})}
  return <Dialog title={quest?'Refine your quest':'A new quest awaits'} close={close}><p>Make it specific. Make it achievable. Make it yours.</p><form onSubmit={submit}><label>Quest title<input autoFocus name="title" defaultValue={quest?.title} required maxLength={120} placeholder="e.g. Read 20 pages of a book"/></label><label>Description <span className="muted">(optional)</span><textarea name="description" defaultValue={quest?.description} maxLength={1000} rows={3} placeholder="What does completing this look like?"/></label><div className="form-grid"><label>Category<select name="category" defaultValue={quest?.category||'STUDY'}>{categories.map(c=><option value={c} key={c}>{label(c)}</option>)}</select></label><label>Difficulty<select name="difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['EASY','MEDIUM','HARD'].map(d=><option value={d} key={d}>{label(d)}</option>)}</select></label></div><label>Due date <span className="muted">(optional)</span><input type="date" name="dueDate" defaultValue={quest?.dueDate||''}/></label><p className="reward-preview"><Sparkles size={17}/> {difficulty==='EASY'?'10 XP + 5 Gold':difficulty==='MEDIUM'?'25 XP + 10 Gold':'50 XP + 20 Gold'}<small>Confirmed by the server when saved</small></p>{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<div className="dialog-actions"><button className="button subtle" type="button" onClick={close}>Cancel</button><button className="button" disabled={mutation.isPending}>{mutation.isPending?'Saving…':quest?'Save changes':'Create quest'}<ArrowRight size={16}/></button></div></form></Dialog>
}
function Pagination({page,pages,setPage}:{page:number;pages:number;setPage:(n:number)=>void}){return <div className="pagination"><button className="icon-button" aria-label="Previous page" disabled={page===0} onClick={()=>setPage(page-1)}><ChevronLeft size={18}/></button><span>Page {page+1} of {Math.max(1,pages)}</span><button className="icon-button" aria-label="Next page" disabled={page+1>=pages} onClick={()=>setPage(page+1)}><ChevronRight size={18}/></button></div>}
function Shop({hero,inventoryOnly,notify,refresh}:{hero:Hero;inventoryOnly:boolean;notify:(n:Notice)=>void;refresh:()=>void}){
  const [slot,setSlot]=useState('ALL')
  const catalog=useQuery({queryKey:[inventoryOnly?'inventory':'shop'],queryFn:()=>api<Item[]>(inventoryOnly?'/inventory':'/shop')})
  const mutation=useMutation({mutationFn:({item,action}:{item:Item;action:string})=>api(action==='buy'?'/shop/'+item.id+'/purchase':'/inventory/'+item.inventoryId+'/'+action,action==='buy'?'POST':'PATCH'),onSuccess:(_,variables)=>{refresh();notify({title:variables.action==='buy'?'A little reward for your hard work.':variables.action==='equip'?'A new look for your next chapter.':'Back to the classics.',detail:variables.item.name})},onError:e=>notify({title:e.message})})
  return <><PageHeading eyebrow={inventoryOnly?'COLLECTED ALONG THE WAY':'EARNED THROUGH EVERYDAY EFFORT'} title={inventoryOnly?'Your collection':'The marketplace'} description={inventoryOnly?'Little reminders of how far you’ve come. Wear your progress.':'A new look, a small celebration. Spend your hard-earned Gold.'} action={<div className="balance"><Coins size={23}/><div><small>YOUR BALANCE</small><strong>{hero.gold} Gold</strong></div></div>}/>{inventoryOnly&&<div className="collection-hero panel"><Character avatar={hero.avatar} cosmetics={hero.cosmetics} small/><div><h2>Your current look</h2><p>{hero.cosmetics.length?hero.cosmetics.map(i=>i.name).join(' · '):'The original adventurer. A classic beginning.'}</p></div></div>}<div className="tabs shop-tabs">{['ALL','FRAME','BADGE','THEME'].map(s=><button key={s} className={slot===s?'active':''} aria-pressed={slot===s} onClick={()=>setSlot(s)}>{s==='ALL'?'All items':label(s)+'s'}</button>)}</div>{catalog.isPending?<Loading/>:catalog.error?<ErrorPanel error={catalog.error} retry={()=>catalog.refetch()}/>:catalog.data?.length?<div className="shop-grid">{catalog.data.filter(i=>slot==='ALL'||i.slot===slot).map(item=><article className="item-card panel" key={item.id}><div className={'item-preview preview-'+item.appearance}>{item.slot==='FRAME'?<Character avatar={hero.avatar} cosmetics={[item]} small/>:item.slot==='BADGE'?<div className="large-badge"><Badge appearance={item.appearance}/></div>:<div className={'theme-mini '+item.appearance}><span/><div><i/><i/><i/></div></div>}{item.equipped&&<span className="equipped-tag"><Check size={12}/> Equipped</span>}</div><div className="item-body"><span className="eyebrow">{item.slot}</span><h2>{item.name}</h2><p>{item.description}</p><div className="item-bottom"><span className="gold-text"><Coins size={16}/>{item.price}</span>{inventoryOnly?<button className={'button '+(item.equipped?'subtle':'')} disabled={mutation.isPending} onClick={()=>mutation.mutate({item,action:item.equipped?'unequip':'equip'})}>{mutation.isPending&&mutation.variables?.item.id===item.id?'Updating…':item.equipped?'Unequip':'Equip'}</button>:<button className={'button '+(item.owned?'subtle':'')} disabled={item.owned||hero.gold<item.price||mutation.isPending} onClick={()=>mutation.mutate({item,action:'buy'})}>{item.owned?<><Check size={15}/> Owned</>:mutation.isPending&&mutation.variables?.item.id===item.id?'Purchasing…':hero.gold<item.price?'Need '+(item.price-hero.gold)+' Gold':'Purchase'}</button>}</div></div></article>)}</div>:<section className="panel"><Empty icon={Backpack} title="Your collection is waiting to grow." text="Complete quests, earn Gold, and find something that feels like you." action={<Link to="/shop" className="button">Visit the marketplace <ArrowRight size={16}/></Link>}/></section>}</>
}
function ActivityList({items}:{items:Activity[]}){return items.length?<div className="activity-list">{items.map(item=>{const league=item.kind==='LEADERBOARD';return <div className="activity-row" key={item.id}><span className={'activity-icon '+(item.kind==='QUEST'?'teal-text':'gold-text')}>{league?<Trophy size={17}/>:item.kind==='QUEST'?<Check size={17}/>:<Store size={17}/>}</span><div><strong>{item.description}</strong><small>{league?'Weekly prize':item.kind==='QUEST'?'Quest completed':'Cosmetic purchased'} · {new Date(item.createdAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></div><span className={item.gold>0?'teal-text':'gold-text'}>{item.xp>0?'+'+item.xp+' XP':''}{item.xp>0&&item.gold!==0?' · ':''}{item.gold!==0?(item.gold>0?'+':'')+item.gold+' Gold':''}</span></div>})}</div>:<Empty icon={BookOpen} title="A blank page, full of possibility." text="Completed quests, weekly prizes, and purchases will become part of your story here."/>}
function Profile({hero,user,notify,refresh,logout}:{hero:Hero;user:User;notify:(n:Notice)=>void;refresh:()=>void;logout:()=>void}){
  const [page,setPage]=useState(0)
  const activity=useQuery({queryKey:['activity',page],queryFn:()=>api<Page<Activity>>('/activity?page='+page)})
  const mutation=useMutation({mutationFn:(body:unknown)=>api('/profile','PATCH',body),onSuccess:()=>{refresh();notify({title:'Your character details are saved.'})}})
  return <><PageHeading eyebrow="THE ADVENTURER BEHIND THE QUESTS" title="Your character, your story" description="Make yourself at home. Look back at the steps that brought you here."/><div className="profile-grid"><section className="panel profile-card"><Character avatar={hero.avatar} cosmetics={hero.cosmetics}/><h2>{hero.displayName}</h2><span className="eyebrow">LEVEL {hero.progress.level} {hero.avatar}</span><div className="profile-stats"><span><strong>{hero.progress.total}</strong>Total XP</span><span><strong>{hero.bestStreak}</strong>Best streak</span><span><strong>{hero.gold}</strong>Gold</span></div><button className="button subtle full" onClick={logout}><LogOut size={16}/> Sign out</button></section><section className="panel settings"><h2>The essentials</h2><p className="muted">{user.email}</p><form onSubmit={e=>{e.preventDefault();mutation.mutate(Object.fromEntries(new FormData(e.currentTarget)))}}><label>Display name<input name="displayName" defaultValue={hero.displayName} maxLength={60} required/></label><label>Character<select name="avatar" defaultValue={hero.avatar}><option value="RANGER">Ranger — steady and curious</option><option value="MAGE">Mage — a spark of possibility</option><option value="KNIGHT">Knight — courage in practice</option></select></label><label>IANA timezone<input name="timezone" defaultValue={hero.pendingTimezone||hero.timezone} list="timezones" required/><datalist id="timezones">{Intl.supportedValuesOf('timeZone').map(z=><option key={z} value={z}/>)}</datalist></label><p className="setting-note">Your timezone defines an activity day. Changes wait until an active day ends, so travelling cannot add extra streak days.{hero.pendingTimezone&&' Pending: '+hero.pendingTimezone+'.'}</p>{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<button className="button" disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save profile'}</button></form></section></div><section className="panel profile-activity"><div className="section-heading"><div><h2>Your adventure log</h2><p>Every reward and purchase, saved as it happened.</p></div><Link className="text-link" to="/quests">Quest history <ArrowUpRight size={15}/></Link></div>{activity.isPending?<Loading/>:activity.error?<ErrorPanel error={activity.error} retry={()=>activity.refetch()}/>:<><ActivityList items={activity.data?.content||[]}/><Pagination page={page} pages={activity.data?.totalPages||0} setPage={setPage}/></>}</section></>
}
